# Understanding Data Received

In this Python Notebook, the team would be opening each CSV file, to read the data and check for missing values and other general cleaning that is required.

In [161]:
# imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import re

import csv
from datetime import datetime

## Understanding 2022 Stats

In [162]:
# view 2022 stats
df_2022 = pd.read_csv("data/2022 Stats.csv")

# print data types of variables
print('Data Types')
print(df_2022.info())

# Display summary statistics
print('\n Summary Statistics')
print(df_2022.describe())

# check any null values
print('\n Check for Null')
print(df_2022.isna().any())

# view data frames
print('\n Dataframe View')
df_2022

Data Types
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           365 non-null    object
 1   Open Balances  365 non-null    int64
 2   Closed         365 non-null    int64
 3   New Cases      365 non-null    int64
dtypes: int64(3), object(1)
memory usage: 11.5+ KB
None

 Summary Statistics
       Open Balances       Closed    New Cases
count     365.000000   365.000000   365.000000
mean     2039.252055   355.506849   443.090411
std       655.385854   262.117368   180.894056
min       688.000000     0.000000    43.000000
25%      1522.000000     6.000000   247.000000
50%      1987.000000   430.000000   491.000000
75%      2560.000000   521.000000   559.000000
max      3394.000000  1146.000000  1212.000000

 Check for Null
Date             False
Open Balances    False
Closed           False
New Cases        False
dtype: bool

 Dataframe View

      Date  Open Balances  Closed  New Cases
0      1/1           1963       0        468
1      2/1           2431       0        503
2      3/1           2934     857       1212
3      4/1           3146     727       1039
4      5/1           3368     949        826
..     ...            ...     ...        ...
360  27/12           3215     520        625
361  28/12           3055     498        558
362  29/12           2965     435        585
363  30/12           2945     356        545
364  31/12           3134      20        201

[365 rows x 4 columns]

### Data Cleaning for 2022 Stats

In [163]:
# create a new dataframe for cleaned data
df_2022_cleaned = df_2022.copy()

# Concatenate the year information to each date string
df_2022_cleaned['Date'] = df_2022_cleaned['Date'] + ' 2022'  # Add the year '2022' assuming all dates are from the same year

# Convert the entire column to datetime objects
df_2022_cleaned['Date'] = pd.to_datetime(df_2022_cleaned['Date'], dayfirst=True)

df_2022_cleaned

          Date  Open Balances  Closed  New Cases
0   2022-01-01           1963       0        468
1   2022-01-02           2431       0        503
2   2022-01-03           2934     857       1212
3   2022-01-04           3146     727       1039
4   2022-01-05           3368     949        826
..         ...            ...     ...        ...
360 2022-12-27           3215     520        625
361 2022-12-28           3055     498        558
362 2022-12-29           2965     435        585
363 2022-12-30           2945     356        545
364 2022-12-31           3134      20        201

[365 rows x 4 columns]

In [164]:
# save cleaned csv
df_2022_cleaned.to_csv('data/2022_Stats_cleaned.csv', index=False)

## Understanding 2023 Stats

In [165]:
# view 2023 stats
df_2023 = pd.read_csv("data/2023 Stats.csv")

# print data types of variables
print('Data Types')
print(df_2023.info())

# Display summary statistics
print('\n Summary Statistics')
print(df_2023.describe())

# check any null values
print('\n Check for Null')
print(df_2023.isna().any())

# view data frames
print('\n Dataframe View')
df_2023

Data Types
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           365 non-null    object
 1   Open Balances  365 non-null    int64
 2   Closed         365 non-null    int64
 3   New Cases      365 non-null    int64
dtypes: int64(3), object(1)
memory usage: 11.5+ KB
None

 Summary Statistics
       Open Balances      Closed   New Cases
count     365.000000  365.000000  365.000000
mean     2353.701370  317.400000  392.005479
std       773.788895  223.133477  160.243239
min      1072.000000    0.000000    0.000000
25%      1755.000000    7.000000  231.000000
50%      2186.000000  386.000000  409.000000
75%      2946.000000  472.000000  493.000000
max      4921.000000  854.000000  867.000000

 Check for Null
Date             False
Open Balances    False
Closed           False
New Cases        False
dtype: bool

 Dataframe View

      Date  Open Balances  Closed  New Cases
0      1/1           3315       5        345
1      2/1           3655      14        588
2      3/1           4229     501        867
3      4/1           4348     526        819
4      5/1           4621     531        778
..     ...            ...     ...        ...
360  27/12           1851     440        514
361  28/12           1831     447        498
362  29/12           1780     426        401
363  30/12           1755       0        232
364  31/12           1987       0        186

[365 rows x 4 columns]

### Data Cleaning for 2023 Stats

In [166]:
# create a new dataframe for cleaned data
df_2023_cleaned = df_2023.copy()

# Concatenate the year information to each date string
df_2023_cleaned['Date'] = df_2023_cleaned['Date'] + ' 2023'  # Add the year '2022' assuming all dates are from the same year

# Convert the entire column to datetime objects
df_2023_cleaned['Date'] = pd.to_datetime(df_2023_cleaned['Date'], dayfirst=True)

df_2023_cleaned

          Date  Open Balances  Closed  New Cases
0   2023-01-01           3315       5        345
1   2023-01-02           3655      14        588
2   2023-01-03           4229     501        867
3   2023-01-04           4348     526        819
4   2023-01-05           4621     531        778
..         ...            ...     ...        ...
360 2023-12-27           1851     440        514
361 2023-12-28           1831     447        498
362 2023-12-29           1780     426        401
363 2023-12-30           1755       0        232
364 2023-12-31           1987       0        186

[365 rows x 4 columns]

In [167]:
# save cleaned csv
df_2023_cleaned.to_csv('data/2023_Stats_cleaned.csv', index=False)

## Understanding All Cases Report

In [168]:
# view all cases report

# Attempt to read the file with different encodings
try:
    with open('data/All Cases Report.csv', 'r', encoding='utf-8') as f:
        data_all_cases_report = f.read()
except UnicodeDecodeError:
    try:
        with open('data/All Cases Report.csv', 'r', encoding='latin-1') as f:
            data_all_cases_report = f.read()
    except UnicodeDecodeError:
        with open('data/All Cases Report.csv', 'r', encoding='cp1252') as f:
            data_all_cases_report = f.read()

# Write the data with the new encoding
with open('data/All Cases Report_encoded.csv', 'w', encoding='utf-8') as f:
    f.write(data_all_cases_report)

# Read the newly encoded CSV file into a DataFrame
df_all_cases_report = pd.read_csv("data/All Cases Report_encoded.csv")

# Print data types of variables
print('Data Types')
print(df_all_cases_report.info())

# Display summary statistics
print('\nSummary Statistics')
print(df_all_cases_report.describe())

# Check for null values
print('\nCheck for Null')
print(df_all_cases_report.isna().any())

# View data frames
print('\nDataframe View')
df_all_cases_report

Data Types
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3133 entries, 0 to 3132
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Group                      3133 non-null   object
 1   Department                 3133 non-null   object
 2   Workbasket                 3133 non-null   object
 3   CAParentInteractionID      1837 non-null   object
 4   Case ID                    3133 non-null   object
 5   Customer Type              2848 non-null   object
 6   Assigned OIC               3133 non-null   object
 7   Case Type                  3133 non-null   object
 8   Case Subtype               3133 non-null   object
 9   Source                     3133 non-null   object
 10  Channel                    3133 non-null   object
 11  Urgency Attributes         3133 non-null   bool
 12  No. of Interim reply sent  50 non-null     float64
 13  Scheme                     3133 non-null   object
 14  Category                   3133 non-null   object
 15  Enquiry                    3133 non-null   object
 16  Status                     3133 non-null   object
 17  Receipt Date               3133 non-null   object
 18  Created Date               3133 non-null   object
 19  Closed Date                3132 non-null   object
 20  Due Date                   3133 non-null   object
dtypes: bool(1), float64(1), object(19)
memory usage: 492.7+ KB
None

Summary Statistics
       No. of Interim reply sent
count                  50.000000
mean                    1.060000
std                     0.424264
min                     1.000000
25%                     1.000000
50%                     1.000000
75%                     1.000000
max                     4.000000

Check for Null
Group                        False
Department                   False
Workbasket                   False
CAParentInteractionID         True
Case ID                      False
Customer Type                 True
Assigned OIC                 False
Case Type                    False
Case Subtype                 False
Source                       False
Channel                      False
Urgency Attributes           False
No. of Interim reply sent     True
Scheme                       False
Category                     False
Enquiry                      False
Status                       False
Receipt Date                 False
Created Date                 False
Closed Date                   True
Due Date                     False
dtype: bool

Dataframe View

,Group,Department,Workbasket,CAParentInteractionID,Case ID,Customer Type,Assigned OIC,Case Type,Case Subtype,Source,...,Urgency Attributes,No. of Interim reply sent,Scheme,Category,Enquiry,Status,Receipt Date,Created Date,Closed Date,Due Date
0,CUG,CCC,[S] Call Centre,I-20240083539,S-20240044663-1,Member,Jasmine Low Boon Hui,Enquiry,Enquiry/Service Request,Mailing Room (Post),...,False,NaN,Member Records,Accounts Management,Latest Statement of Account (SOA),Resolved Completed,26/1/24,7/2/24,7/2/24,9/2/24
1,CUG,CCC,[S] CCU-Retirement,NaN,S-20240037223-3,Member,Edel Ngo Xuan Yun,Appeal,CPF Schemes,External Agencies - MP,...,False,NaN,Retirement,55 Withdrawal,S15 Topping up upon 55 withdrawal,Resolved Completed,23/1/24,6/2/24,6/2/24,6/2/24
2,CUG,CCC,[S] CCU-Retirement,I-20240071430,S-20240038527-2,Member,J S Rosanah Begum,Enquiry,Enquiry/Service Request,Customer Correspondence Unit,...,False,NaN,Retirement,Multiple retirement-related CPF schemes,Enquiry/Request on CPF Retirement Sum and Reti...,Resolved Completed,23/1/24,6/2/24,8/2/24,14/2/24
3,CUG,CCC,[S] CCU-Healthcare,NaN,S-20240041998-1,Member,J S Rosanah Begum,Appeal,CPF Schemes,External Agencies - MP,...,True,NaN,MediSave,Withdrawals & Usage,General Enquiries on MediSave Scheme,Resolved Completed,25/1/24,2/2/24,5/2/24,8/3/24
4,CUG,CCC,[S] CCU-Nomination,NaN,S-20240044717-1,Member,Matthew Kar Pui Him,Enquiry,Enquiry/Service Request,My Mailbox,...,False,NaN,Nomination,Deceased Cases,Enquire deceased's nomination,Resolved Completed,26/1/24,1/2/24,1/2/24,2/2/24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3128,CUG,CCC,[S] CCU-Withdrawal,I-20240065578,S-20240034879,Member,Paul Melki Hong Zhen Yang,Enquiry,Enquiry/Service Request,Website,...,False,NaN,Account Closure,LM Withdrawal,Status of application,Resolved Completed,21/1/24,21/1/24,24/1/24,26/1/24
3129,CUG,CCC,[S] CCU-Withdrawal,I-20240065428,S-20240034690,Member,Paul Melki Hong Zhen Yang,Enquiry,Enquiry/Service Request,Website,...,False,NaN,Account Closure,LM Withdrawal,Account closure application process,Resolved Completed,21/1/24,21/1/24,25/1/24,26/1/24
3130,CUG,CCC,[S] CCU-Withdrawal,I-20240065544,S-20240034830,Member,TIFFANY TUNG WEI TZE,Enquiry,Enquiry/Service Request,Website,...,False,NaN,Account Closure,LM Withdrawal,Status of application,Resolved Completed,21/1/24,21/1/24,24/1/24,26/1/24
3131,CUG,CCC,[S] CCU-Withdrawal,I-20240065586,S-20240034889,Member,TIFFANY TUNG WEI TZE,Enquiry,Enquiry/Service Request,Website,...,False,NaN,Account Closure,LM Withdrawal,Account closure application process,Resolved Completed,21/1/24,21/1/24,24/1/24,26/1/24
3132,CUG,CCC,[S] CCU-Withdrawal,I-20240065602,S-20240034922,Member,TIFFANY TUNG WEI TZE,Enquiry,Enquiry/Service Request,Website,...,False,NaN,Account Closure,LM Withdrawal,Account closure application process,Resolved Completed,21/1/24,21/1/24,24/1/24,26/1/24

### Data Cleaning for All Cases Report

In [169]:
# create a new dataframe for cleaned data
df_all_cases_report_cleaned = df_all_cases_report.copy()

# replace all NaN with 0 for No. of Interim replies sent
df_all_cases_report_cleaned['No. of Interim reply sent'] = df_all_cases_report['No. of Interim reply sent'].fillna(0)

# dropped CAParentInteractionID because not necessary
df_all_cases_report_cleaned = df_all_cases_report_cleaned.drop(columns=['CAParentInteractionID'])

# turn NaN customer types into "Not Specified"
df_all_cases_report_cleaned['Customer Type'] = df_all_cases_report['Customer Type'].fillna('Not Specified')

# turn NaN closed dates into a random future closed data to indicate that it is unclosed
future_date = pd.to_datetime('2025-01-01')
df_all_cases_report_cleaned['Closed Date'].fillna(future_date, inplace=True)

# turn all date columns into datetime64[ns]
df_all_cases_report_cleaned['Receipt Date'] = pd.to_datetime(df_all_cases_report_cleaned['Receipt Date'], dayfirst=True)
df_all_cases_report_cleaned['Created Date'] = pd.to_datetime(df_all_cases_report_cleaned['Created Date'], dayfirst=True)
df_all_cases_report_cleaned['Closed Date'] = pd.to_datetime(df_all_cases_report_cleaned['Closed Date'], dayfirst=True)
df_all_cases_report_cleaned['Due Date'] = pd.to_datetime(df_all_cases_report_cleaned['Due Date'], dayfirst=True)

df_all_cases_report_cleaned

,Group,Department,Workbasket,Case ID,Customer Type,Assigned OIC,Case Type,Case Subtype,Source,Channel,Urgency Attributes,No. of Interim reply sent,Scheme,Category,Enquiry,Status,Receipt Date,Created Date,Closed Date,Due Date
0,CUG,CCC,[S] Call Centre,S-20240044663-1,Member,Jasmine Low Boon Hui,Enquiry,Enquiry/Service Request,Mailing Room (Post),Letter,False,0.0,Member Records,Accounts Management,Latest Statement of Account (SOA),Resolved Completed,2024-01-26,2024-02-07,2024-02-07,2024-02-09
1,CUG,CCC,[S] CCU-Retirement,S-20240037223-3,Member,Edel Ngo Xuan Yun,Appeal,CPF Schemes,External Agencies - MP,MPAS,False,0.0,Retirement,55 Withdrawal,S15 Topping up upon 55 withdrawal,Resolved Completed,2024-01-23,2024-02-06,2024-02-06,2024-02-06
2,CUG,CCC,[S] CCU-Retirement,S-20240038527-2,Member,J S Rosanah Begum,Enquiry,Enquiry/Service Request,Customer Correspondence Unit,e-Services,False,0.0,Retirement,Multiple retirement-related CPF schemes,Enquiry/Request on CPF Retirement Sum and Reti...,Resolved Completed,2024-01-23,2024-02-06,2024-02-08,2024-02-14
3,CUG,CCC,[S] CCU-Healthcare,S-20240041998-1,Member,J S Rosanah Begum,Appeal,CPF Schemes,External Agencies - MP,Email,True,0.0,MediSave,Withdrawals & Usage,General Enquiries on MediSave Scheme,Resolved Completed,2024-01-25,2024-02-02,2024-02-05,2024-03-08
4,CUG,CCC,[S] CCU-Nomination,S-20240044717-1,Member,Matthew Kar Pui Him,Enquiry,Enquiry/Service Request,My Mailbox,e-Services,False,0.0,Nomination,Deceased Cases,Enquire deceased's nomination,Resolved Completed,2024-01-26,2024-02-01,2024-02-01,2024-02-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3128,CUG,CCC,[S] CCU-Withdrawal,S-20240034879,Member,Paul Melki Hong Zhen Yang,Enquiry,Enquiry/Service Request,Website,e-Services,False,0.0,Account Closure,LM Withdrawal,Status of application,Resolved Completed,2024-01-21,2024-01-21,2024-01-24,2024-01-26
3129,CUG,CCC,[S] CCU-Withdrawal,S-20240034690,Member,Paul Melki Hong Zhen Yang,Enquiry,Enquiry/Service Request,Website,e-Services,False,0.0,Account Closure,LM Withdrawal,Account closure application process,Resolved Completed,2024-01-21,2024-01-21,2024-01-25,2024-01-26
3130,CUG,CCC,[S] CCU-Withdrawal,S-20240034830,Member,TIFFANY TUNG WEI TZE,Enquiry,Enquiry/Service Request,Website,e-Services,False,0.0,Account Closure,LM Withdrawal,Status of application,Resolved Completed,2024-01-21,2024-01-21,2024-01-24,2024-01-26
3131,CUG,CCC,[S] CCU-Withdrawal,S-20240034889,Member,TIFFANY TUNG WEI TZE,Enquiry,Enquiry/Service Request,Website,e-Services,False,0.0,Account Closure,LM Withdrawal,Account closure application process,Resolved Completed,2024-01-21,2024-01-21,2024-01-24,2024-01-26
3132,CUG,CCC,[S] CCU-Withdrawal,S-20240034922,Member,TIFFANY TUNG WEI TZE,Enquiry,Enquiry/Service Request,Website,e-Services,False,0.0,Account Closure,LM Withdrawal,Account closure application process,Resolved Completed,2024-01-21,2024-01-21,2024-01-24,2024-01-26

In [170]:
# save cleaned csv
df_all_cases_report_cleaned.to_csv('data/All_Cases_Report_cleaned.csv', index=False)

## Understanding All Closed Cases Report

In [171]:
# view all closed cases report

# Attempt to read the file with different encodings
try:
    with open('data/All Closed Cases Report.csv', 'r', encoding='utf-8') as f:
        data_all_closed_cases = f.read()
except UnicodeDecodeError:
    try:
        with open('data/All Closed Cases Report.csv', 'r', encoding='latin-1') as f:
            data_all_closed_cases = f.read()
    except UnicodeDecodeError:
        with open('data/All Closed Cases Report.csv', 'r', encoding='cp1252') as f:
            data_all_closed_cases = f.read()

# Write the data with the new encoding
with open('data/All Closed Cases Report_encoded.csv', 'w', encoding='utf-8') as f:
    f.write(data_all_closed_cases)

# Read the newly encoded CSV file into a DataFrame
df_all_closed_cases = pd.read_csv("data/All Closed Cases Report_encoded.csv")

# print data types of variables
print('Data Types')
print(df_all_closed_cases.info())

# Display summary statistics
print('\n Summary Statistics')
print(df_all_closed_cases.describe())

# check any null values
print('\n Check for Null')
print(df_all_closed_cases.isna().any())

# view data frames
print('\n Dataframe View')
df_all_closed_cases

Data Types
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2578 entries, 0 to 2577
Data columns (total 29 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Group                                     2578 non-null   object
 1   Department                                2578 non-null   object
 2   Workbasket                                2578 non-null   object
 3   Case ID                                   2578 non-null   object
 4   Parent/Child                              2578 non-null   object
 5   Customer Type                             2467 non-null   object
 6   Assigned OIC                              2578 non-null   object
 7   Case Type                                 2578 non-null   object
 8   Case Subtype                              2578 non-null   object
 9   Source                                    2578 non-null   object
 10  Channel                                   2578 non-null   object
 11  Urgency Attributes                        2578 non-null   bool
 12  No. of Interim reply sent                 165 non-null    float64
 13  Scheme                                    2578 non-null   object
 14  Category                                  2578 non-null   object
 15  Enquiry                                   2578 non-null   object
 16  Outcome                                   2495 non-null   object
 17  Outcome Details                           2495 non-null   object
 18  Receipt Date                              2578 non-null   object
 19  Created Date                              2578 non-null   object
 20  Closed Date                               2578 non-null   object
 21  Due Date                                  2578 non-null   object
 22  Total Days For Resolution                 2578 non-null   int64
 23  Exceeds SLA by how many days              2578 non-null   int64
 24  No of Replies Sent to Customer (Final)    2578 non-null   int64
 25  No of Replies Sent to Customer (Interim)  2578 non-null   int64
 26  No of Replies Sent to Others (Final)      2578 non-null   int64
 27  No of Replies Sent to Others (Interim)    2578 non-null   int64
 28  Total Replies                             2578 non-null   int64
dtypes: bool(1), float64(1), int64(7), object(20)
memory usage: 566.6+ KB
None

 Summary Statistics
       No. of Interim reply sent  Total Days For Resolution  \
count                 165.000000                2578.000000
mean                    1.012121                   3.076028
std                     0.109760                   4.730416
min                     1.000000                   0.000000
25%                     1.000000                   0.000000
50%                     1.000000                   2.000000
75%                     1.000000                   4.000000
max                     2.000000                  41.000000

       Exceeds SLA by how many days  No of Replies Sent to Customer (Final)  \
count                   2578.000000                             2578.000000
mean                      -3.576804                                0.566330
std                        3.699904                                0.510335
min                      -23.000000                                0.000000
25%                       -5.000000                                0.000000
50%                       -4.000000                                1.000000
75%                       -1.000000                                1.000000
max                       26.000000                                2.000000

       No of Replies Sent to Customer (Interim)  \
count                               2578.000000
mean                                   0.020559
std                                    0.147295
min                                    0.000000
25%                                    0.000000
50%                                    0.000000
75%                                    0.000000
max                                    2.000000

       No of Replies Sent to Others (Final)  \
count                           2578.000000
mean                               0.049263
std                                0.226960
min                                0.000000
25%                                0.000000
50%                                0.000000
75%                                0.000000
max                                2.000000

       No of Replies Sent to Others (Interim)  Total Replies
count                             2578.000000    2578.000000
mean                                 0.041505       0.677657
std                                  0.199494       0.599810
min                                  0.000000       0.000000
25%                                  0.000000       0.000000
50%                                  0.000000       1.000000
75%                                  0.000000       1.000000
max                                  1.000000       4.000000

 Check for Null
Group                                       False
Department                                  False
Workbasket                                  False
Case ID                                     False
Parent/Child                                False
Customer Type                                True
Assigned OIC                                False
Case Type                                   False
Case Subtype                                False
Source                                      False
Channel                                     False
Urgency Attributes                          False
No. of Interim reply sent                    True
Scheme                                      False
Category                                    False
Enquiry                                     False
Outcome                                      True
Outcome Details                              True
Receipt Date                                False
Created Date                                False
Closed Date                                 False
Due Date                                    False
Total Days For Resolution                   False
Exceeds SLA by how many days                False
No of Replies Sent to Customer (Final)      False
No of Replies Sent to Customer (Interim)    False
No of Replies Sent to Others (Final)        False
No of Replies Sent to Others (Interim)      False
Total Replies                               False
dtype: bool

 Dataframe View

,Group,Department,Workbasket,Case ID,Parent/Child,Customer Type,Assigned OIC,Case Type,Case Subtype,Source,...,Created Date,Closed Date,Due Date,Total Days For Resolution,Exceeds SLA by how many days,No of Replies Sent to Customer (Final),No of Replies Sent to Customer (Interim),No of Replies Sent to Others (Final),No of Replies Sent to Others (Interim),Total Replies
0,ASG,SED,[S] SE Collection,S-20240085039-1,Child,Member,Darren Kum Wen Hao,Enquiry,Enquiry/Service Request,My Mailbox,...,26/2/24,26/2/24,28/2/24,3,-2,0,0,0,0,0
1,ASG,SED,[S] SE Instalment,S-20240090859,Parent,Member,Christina Sim Lay Khoon,Enquiry,Enquiry/Service Request,My Mailbox,...,26/2/24,26/2/24,4/3/24,0,-5,1,0,0,0,1
2,ASG,SED,[S] SE Instalment,S-20240090864,Parent,Member,Irene Chua Li Na,Appeal,Healthcare Schemes,My Mailbox,...,26/2/24,26/2/24,4/3/24,0,-5,1,0,0,0,1
3,ASG,SED,[S] SE Instalment,S-20240091000,Parent,Member,Irene Chua Li Na,Enquiry,Enquiry/Service Request,Backend Systems,...,26/2/24,26/2/24,1/3/24,0,-4,0,0,0,0,0
4,ASG,SED,[S] SE Instalment,S-20240091040,Parent,Member,Neo Hui Fen,Appeal,CPF Schemes,My Mailbox,...,26/2/24,26/2/24,4/3/24,0,-5,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2573,ASG,AMD,[S] Workfare Appeal,S-20240024137,Parent,Member,Ven Chng Boon Chye,Appeal,Agency Schemes,My Mailbox,...,15/1/24,26/2/24,23/2/24,29,1,1,1,0,0,2
2574,ASG,AMD,[S] Silver Support Appeal,S-20240022842,Parent,Member,Brina Lau Kai Ting,Appeal,Agency Schemes,External Agencies - MP,...,14/1/24,26/2/24,26/2/24,29,0,1,1,0,0,2
2575,RIG,RWD,[S] RS Payout,S-20240022424,Parent,Member,Ong Ming Zhu,Appeal,CPF Schemes,External Agencies - MP,...,13/1/24,26/2/24,26/2/24,29,0,1,1,1,0,3
2576,ASG,AMD,[S] Silver Support Appeal,S-20240020847,Parent,Member,Juraimi Bin Jamil,Appeal,Agency Schemes,Website,...,12/1/24,26/2/24,22/2/24,30,2,2,0,0,1,3
2577,HFG,HCP,[S] MediSave Withdrawals & Usage,S-20230508683,Parent,Member,Evelyn Lim Yu Ling,Enquiry,Enquiry/Service Request,Call Centre,...,27/12/23,26/2/24,18/1/24,41,26,1,2,0,0,3

### Data Cleaning for All Closed Cases Report

In [172]:
# create a new dataframe for cleaned data
df_all_closed_cases_cleaned = df_all_closed_cases.copy()

# replace all NaN with 0 for No. of Interim replies sent
df_all_closed_cases_cleaned['No. of Interim reply sent'] = df_all_closed_cases_cleaned['No. of Interim reply sent'].fillna(0)

# turn NaN customer types into "Not Specified"
df_all_closed_cases_cleaned['Customer Type'] = df_all_closed_cases_cleaned['Customer Type'].fillna('Not Specified')

# # turn all date columns into datetime64[ns]
df_all_closed_cases_cleaned['Receipt Date'] = pd.to_datetime(df_all_closed_cases_cleaned['Receipt Date'], dayfirst=True)
df_all_closed_cases_cleaned['Created Date'] = pd.to_datetime(df_all_closed_cases_cleaned['Created Date'], dayfirst=True)
df_all_closed_cases_cleaned['Closed Date'] = pd.to_datetime(df_all_closed_cases_cleaned['Closed Date'], dayfirst=True)
df_all_closed_cases_cleaned['Due Date'] = pd.to_datetime(df_all_closed_cases_cleaned['Due Date'], dayfirst=True)

# dropped NaN Outcomes and Outcome Details
df_all_closed_cases_cleaned = df_all_closed_cases_cleaned.dropna(subset='Outcome')
df_all_closed_cases_cleaned = df_all_closed_cases_cleaned.dropna(subset='Outcome Details')
print(df_all_closed_cases_cleaned.isna().any())
df_all_closed_cases_cleaned

Group                                       False
Department                                  False
Workbasket                                  False
Case ID                                     False
Parent/Child                                False
Customer Type                               False
Assigned OIC                                False
Case Type                                   False
Case Subtype                                False
Source                                      False
Channel                                     False
Urgency Attributes                          False
No. of Interim reply sent                   False
Scheme                                      False
Category                                    False
Enquiry                                     False
Outcome                                     False
Outcome Details                             False
Receipt Date                                False
Created Date                                False
Closed Date                                 False
Due Date                                    False
Total Days For Resolution                   False
Exceeds SLA by how many days                False
No of Replies Sent to Customer (Final)      False
No of Replies Sent to Customer (Interim)    False
No of Replies Sent to Others (Final)        False
No of Replies Sent to Others (Interim)      False
Total Replies                               False
dtype: bool

,Group,Department,Workbasket,Case ID,Parent/Child,Customer Type,Assigned OIC,Case Type,Case Subtype,Source,...,Created Date,Closed Date,Due Date,Total Days For Resolution,Exceeds SLA by how many days,No of Replies Sent to Customer (Final),No of Replies Sent to Customer (Interim),No of Replies Sent to Others (Final),No of Replies Sent to Others (Interim),Total Replies
1,ASG,SED,[S] SE Instalment,S-20240090859,Parent,Member,Christina Sim Lay Khoon,Enquiry,Enquiry/Service Request,My Mailbox,...,2024-02-26,2024-02-26,2024-03-04,0,-5,1,0,0,0,1
2,ASG,SED,[S] SE Instalment,S-20240090864,Parent,Member,Irene Chua Li Na,Appeal,Healthcare Schemes,My Mailbox,...,2024-02-26,2024-02-26,2024-03-04,0,-5,1,0,0,0,1
3,ASG,SED,[S] SE Instalment,S-20240091000,Parent,Member,Irene Chua Li Na,Enquiry,Enquiry/Service Request,Backend Systems,...,2024-02-26,2024-02-26,2024-03-01,0,-4,0,0,0,0,0
4,ASG,SED,[S] SE Instalment,S-20240091040,Parent,Member,Neo Hui Fen,Appeal,CPF Schemes,My Mailbox,...,2024-02-26,2024-02-26,2024-03-04,0,-5,0,0,0,0,0
5,ASG,SED,[S] SE Instalment,S-20240091711,Parent,Member,Irene Chua Li Na,Appeal,CPF Schemes,My Mailbox,...,2024-02-26,2024-02-26,2024-03-04,0,-5,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2573,ASG,AMD,[S] Workfare Appeal,S-20240024137,Parent,Member,Ven Chng Boon Chye,Appeal,Agency Schemes,My Mailbox,...,2024-01-15,2024-02-26,2024-02-23,29,1,1,1,0,0,2
2574,ASG,AMD,[S] Silver Support Appeal,S-20240022842,Parent,Member,Brina Lau Kai Ting,Appeal,Agency Schemes,External Agencies - MP,...,2024-01-14,2024-02-26,2024-02-26,29,0,1,1,0,0,2
2575,RIG,RWD,[S] RS Payout,S-20240022424,Parent,Member,Ong Ming Zhu,Appeal,CPF Schemes,External Agencies - MP,...,2024-01-13,2024-02-26,2024-02-26,29,0,1,1,1,0,3
2576,ASG,AMD,[S] Silver Support Appeal,S-20240020847,Parent,Member,Juraimi Bin Jamil,Appeal,Agency Schemes,Website,...,2024-01-12,2024-02-26,2024-02-22,30,2,2,0,0,1,3
2577,HFG,HCP,[S] MediSave Withdrawals & Usage,S-20230508683,Parent,Member,Evelyn Lim Yu Ling,Enquiry,Enquiry/Service Request,Call Centre,...,2023-12-27,2024-02-26,2024-01-18,41,26,1,2,0,0,3

In [173]:
# save cleaned csv
df_all_closed_cases_cleaned.to_csv('data/All_Closed_Cases_Report_cleaned.csv', index=False)

## Understanding Case Closure

In [174]:
# view case closure csv

# Attempt to read the file with different encodings
try:
    with open('data/Case Closure.csv', 'r', encoding='utf-8') as f:
        data_case_closure = f.read()
except UnicodeDecodeError:
    try:
        with open('data/Case Closure.csv', 'r', encoding='latin-1') as f:
            data_case_closure = f.read()
    except UnicodeDecodeError:
        with open('data/Case Closure.csv', 'r', encoding='cp1252') as f:
            data_case_closure = f.read()

# Write the data with the new encoding
with open('data/Case Closure_encoded.csv', 'w', encoding='utf-8') as f:
    f.write(data_case_closure)

# Read the newly encoded CSV file into a DataFrame
df_case_closure = pd.read_csv("data/Case Closure_encoded.csv")

# print data types of variables
print('Data Types')
print(df_case_closure.info())

# Display summary statistics
print('\n Summary Statistics')
print(df_case_closure.describe())

# check any null values
print('\n Check for Null')
print(df_case_closure.isna().any())

# view data frames
print('\n Dataframe View')
df_case_closure

Data Types
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 514 entries, 0 to 513
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         487 non-null    object
 1   Avg Case Closed Per CSE      487 non-null    float64
 2   Avg Case Closed Per CSA      487 non-null    float64
 3   Avg Case Closed Per TL       487 non-null    float64
 4   Avg Case Closed per Temp     487 non-null    float64
 5   Average Case Closed per CfS  487 non-null    float64
 6   Avg Case Closed per Sup      487 non-null    float64
 7   Unnamed: 7                   0 non-null      float64
 8   Unnamed: 8                   0 non-null      float64
 9   Unnamed: 9                   0 non-null      float64
 10  Unnamed: 10                  0 non-null      float64
 11  Unnamed: 11                  0 non-null      float64
 12  Unnamed: 12                  0 non-null      float64
 13  Unnamed: 13                  0 non-null      float64
 14  Unnamed: 14                  0 non-null      float64
 15  Unnamed: 15                  0 non-null      float64
 16  Unnamed: 16                  0 non-null      float64
 17  Unnamed: 17                  0 non-null      float64
 18  Unnamed: 18                  0 non-null      float64
 19  Unnamed: 19                  0 non-null      float64
 20  Unnamed: 20                  0 non-null      float64
 21  Unnamed: 21                  0 non-null      float64
 22  Unnamed: 22                  0 non-null      float64
 23  Unnamed: 23                  0 non-null      float64
 24  Unnamed: 24                  1 non-null      object
dtypes: float64(23), object(2)
memory usage: 100.5+ KB
None

 Summary Statistics
       Avg Case Closed Per CSE  Avg Case Closed Per CSA  \
count               487.000000               487.000000
mean                 21.149897                 4.899384
std                  12.918712                 8.330131
min                   0.000000                 0.000000
25%                   6.000000                 0.000000
50%                  27.000000                 0.000000
75%                  30.000000                11.500000
max                  44.000000                28.000000

       Avg Case Closed Per TL  Avg Case Closed per Temp  \
count              487.000000                487.000000
mean                 8.199179                  8.560575
std                 10.852327                 16.932811
min                  0.000000                  0.000000
25%                  0.000000                  0.000000
50%                  4.000000                  0.000000
75%                 12.000000                 14.000000
max                 45.000000                224.000000

       Average Case Closed per CfS  Avg Case Closed per Sup  Unnamed: 7  \
count                   487.000000               487.000000         0.0
mean                      0.657084                 0.414784         NaN
std                       3.435392                 3.689662         NaN
min                       0.000000                 0.000000         NaN
25%                       0.000000                 0.000000         NaN
50%                       0.000000                 0.000000         NaN
75%                       0.000000                 0.000000         NaN
max                      24.000000                63.000000         NaN

       Unnamed: 8  Unnamed: 9  Unnamed: 10  ...  Unnamed: 14  Unnamed: 15  \
count         0.0         0.0          0.0  ...          0.0          0.0
mean          NaN         NaN          NaN  ...          NaN          NaN
std           NaN         NaN          NaN  ...          NaN          NaN
min           NaN         NaN          NaN  ...          NaN          NaN
25%           NaN         NaN          NaN  ...          NaN          NaN
50%           NaN         NaN          NaN  ...          NaN          NaN
75%           NaN         NaN          NaN  ...          NaN          NaN
max           NaN         NaN          NaN  ...          NaN          NaN

       Unnamed: 16  Unnamed: 17  Unnamed: 18  Unnamed: 19  Unnamed: 20  \
count          0.0          0.0          0.0          0.0          0.0
mean           NaN          NaN          NaN          NaN          NaN
std            NaN          NaN          NaN          NaN          NaN
min            NaN          NaN          NaN          NaN          NaN
25%            NaN          NaN          NaN          NaN          NaN
50%            NaN          NaN          NaN          NaN          NaN
75%            NaN          NaN          NaN          NaN          NaN
max            NaN          NaN          NaN          NaN          NaN

       Unnamed: 21  Unnamed: 22  Unnamed: 23
count          0.0          0.0          0.0
mean           NaN          NaN          NaN
std            NaN          NaN          NaN
min            NaN          NaN          NaN
25%            NaN          NaN          NaN
50%            NaN          NaN          NaN
75%            NaN          NaN          NaN
max            NaN          NaN          NaN

[8 rows x 23 columns]

 Check for Null
Date                           True
Avg Case Closed Per CSE        True
Avg Case Closed Per CSA        True
Avg Case Closed Per TL         True
Avg Case Closed per Temp       True
Average Case Closed per CfS    True
Avg Case Closed per Sup        True
Unnamed: 7                     True
Unnamed: 8                     True
Unnamed: 9                     True
Unnamed: 10                    True
Unnamed: 11                    True
Unnamed: 12                    True
Unnamed: 13                    True
Unnamed: 14                    True
Unnamed: 15                    True
Unnamed: 16                    True
Unnamed: 17                    True
Unnamed: 18                    True
Unnamed: 19                    True
Unnamed: 20                    True
Unnamed: 21                    True
Unnamed: 22                    True
Unnamed: 23                    True
Unnamed: 24                    True
dtype: bool

 Dataframe View

,Date,Avg Case Closed Per CSE,Avg Case Closed Per CSA,Avg Case Closed Per TL,Avg Case Closed per Temp,Average Case Closed per CfS,Avg Case Closed per Sup,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,2-Oct (Sun),0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3-Oct (Mon),28.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4-Oct (Tue),28.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5-Oct (Wed),28.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6-Oct (Thu),28.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
511,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
513,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Data Cleaning for Case Closure

In [175]:
df_case_closure_cleaned = df_case_closure.copy()

# Drop columns from position 3 onwards
columns_to_drop = df_case_closure_cleaned.columns[7:]  # Get column names starting from position 3 onwards
df_case_closure_cleaned = df_case_closure_cleaned.drop(columns=columns_to_drop)

# drop all NaN values
df_case_closure_cleaned = df_case_closure_cleaned.dropna()

df_case_closure_cleaned

,Date,Avg Case Closed Per CSE,Avg Case Closed Per CSA,Avg Case Closed Per TL,Avg Case Closed per Temp,Average Case Closed per CfS,Avg Case Closed per Sup
0,2-Oct (Sun),0.0,0.0,0.0,0.0,0.0,0.0
1,3-Oct (Mon),28.0,0.0,0.0,0.0,0.0,0.0
2,4-Oct (Tue),28.0,0.0,0.0,0.0,0.0,0.0
3,5-Oct (Wed),28.0,0.0,0.0,0.0,0.0,0.0
4,6-Oct (Thu),28.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
482,27 Jan (Sat),0.0,0.0,0.0,0.0,0.0,0.0
483,28 Jan (Sun),6.0,0.0,0.0,0.0,0.0,0.0
484,29 Jan (Mon),29.0,23.0,13.0,14.0,13.0,3.0
485,30 Jan (Tue),26.0,20.0,13.0,7.0,21.0,0.0
486,31 Jan (Wed),24.0,22.0,6.0,8.0,21.0,4.0

In [176]:
# change date type

# Add the year information for each date string
start_year = 2022  # Start year of your data
end_year = 2024    # End year of your data
years = list(range(start_year, end_year + 1))  # Create a list of years
year_index = 0

pattern = r'(\d{1,2})\s?(\w{3})'
pattern1 = r'(\d{1,2})-?(\w{3})'

# Convert each date string to datetime objects
for i, date_str in enumerate(df_case_closure_cleaned['Date']):
    match = re.match(pattern, date_str)
    match1 = re.match(pattern1, date_str)

    if match:
        # Extract day and month using regular expressions
        day, month_abbr = match.groups()
    elif match1:
        day, month_abbr = match1.groups()
    else:
        # Extract day and month from the date string without hyphen
        day, month_abbr = date_str.split()[0], date_str.split()[1]


    month = pd.to_datetime(month_abbr, format='%b').month
    year = years[year_index]

    # Concatenate the components to form a date string in the format YYYY-MM-DD
    date_formatted = f"{year}-{month:02d}-{day}"

    # Convert the formatted date string to a datetime object and update the column
    df_case_closure_cleaned.at[i, 'Date'] = pd.to_datetime(date_formatted, dayfirst=True).date()

    # Update the year index if the month is December
    if day =='31' and month_abbr == 'Dec':
        year_index += 1

df_case_closure_cleaned

,Date,Avg Case Closed Per CSE,Avg Case Closed Per CSA,Avg Case Closed Per TL,Avg Case Closed per Temp,Average Case Closed per CfS,Avg Case Closed per Sup
0,2022-10-02,0.0,0.0,0.0,0.0,0.0,0.0
1,2022-10-03,28.0,0.0,0.0,0.0,0.0,0.0
2,2022-10-04,28.0,0.0,0.0,0.0,0.0,0.0
3,2022-10-05,28.0,0.0,0.0,0.0,0.0,0.0
4,2022-10-06,28.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
482,2024-01-27,0.0,0.0,0.0,0.0,0.0,0.0
483,2024-01-28,6.0,0.0,0.0,0.0,0.0,0.0
484,2024-01-29,29.0,23.0,13.0,14.0,13.0,3.0
485,2024-01-30,26.0,20.0,13.0,7.0,21.0,0.0
486,2024-01-31,24.0,22.0,6.0,8.0,21.0,4.0

In [177]:
# save cleaned csv
df_case_closure_cleaned.to_csv('data/Case_Closure_(Oct22-Jan24)_cleaned.csv', index=False)

## Understanding Correspondence Report

In [178]:
# view case closure csv

# Attempt to read the file with different encodings
try:
    with open('data/Correspondence_Report.csv', 'r', encoding='utf-8') as f:
        data_correspondence = f.read()
except UnicodeDecodeError:
    try:
        with open('data/Correspondence_Report.csv', 'r', encoding='latin-1') as f:
            data_correspondence = f.read()
    except UnicodeDecodeError:
        with open('data/Correspondence_Report.csv', 'r', encoding='cp1252') as f:
            data_correspondence = f.read()

# Write the data with the new encoding
with open('data/Correspondence_Report_encoded.csv', 'w', encoding='utf-8') as f:
    f.write(data_correspondence)

# Read the newly encoded CSV file into a DataFrame
df_correspondence = pd.read_csv("data/Correspondence_Report_encoded.csv")

# print data types of variables
print('Data Types')
print(df_correspondence.info())

# Display summary statistics
print('\n Summary Statistics')
print(df_correspondence.describe())

# check any null values
print('\n Check for Null')
print(df_correspondence.isna().any())

# view data frames
print('\n Dataframe View')
df_correspondence

Data Types
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2580 entries, 0 to 2579
Data columns (total 35 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Group                         2580 non-null   object
 1   Department                    2580 non-null   object
 2   Workbasket                    2580 non-null   object
 3   Case ID                       2580 non-null   object
 4   Parent/Child                  2580 non-null   object
 5   CustomerType                  2460 non-null   object
 6   Assigned OIC                  2580 non-null   object
 7   Case Type                     2580 non-null   object
 8   SubCategory                   2580 non-null   object
 9   Outcome                       2580 non-null   object
 10  Source                        2580 non-null   object
 11  Channel                       2580 non-null   object
 12  Mode                          2580 non-null   object
 13  Label                         2580 non-null   object
 14  Scheme                        2580 non-null   object
 15  Category                      2580 non-null   object
 16  Enquiry                       2579 non-null   object
 17  ReceiptDate                   2580 non-null   object
 18  Created Date                  2580 non-null   object
 19  Closed Date                   2580 non-null   object
 20  Due Date                      2579 non-null   object
 21  Total Days For Resolution     2580 non-null   int64
 22  Exceeds SLA by how many days  2580 non-null   int64
 23  ApproverName1                 92 non-null     object
 24  ApproverName2                 6 non-null      object
 25  ApproverName3                 0 non-null      float64
 26  ApproverName4                 0 non-null      float64
 27  ApproverName5                 0 non-null      float64
 28  ApproverName6                 0 non-null      float64
 29  ReviewerName1                 211 non-null    object
 30  ReviewerName2                 2 non-null      object
 31  ReviewerName3                 0 non-null      float64
 32  ReviewerName4                 0 non-null      float64
 33  ReviewerName5                 0 non-null      float64
 34  ReviewerName6                 0 non-null      float64
dtypes: float64(8), int64(2), object(25)
memory usage: 705.6+ KB
None

 Summary Statistics
       Total Days For Resolution  Exceeds SLA by how many days  ApproverName3  \
count                2580.000000                   2580.000000            0.0
mean                    3.986047                     -3.006589            NaN
std                     5.408246                      3.389128            NaN
min                     0.000000                    -23.000000            NaN
25%                     1.000000                     -4.000000            NaN
50%                     3.000000                     -3.000000            NaN
75%                     5.000000                     -1.000000            NaN
max                    41.000000                     26.000000            NaN

       ApproverName4  ApproverName5  ApproverName6  ReviewerName3  \
count            0.0            0.0            0.0            0.0
mean             NaN            NaN            NaN            NaN
std              NaN            NaN            NaN            NaN
min              NaN            NaN            NaN            NaN
25%              NaN            NaN            NaN            NaN
50%              NaN            NaN            NaN            NaN
75%              NaN            NaN            NaN            NaN
max              NaN            NaN            NaN            NaN

       ReviewerName4  ReviewerName5  ReviewerName6
count            0.0            0.0            0.0
mean             NaN            NaN            NaN
std              NaN            NaN            NaN
min              NaN            NaN            NaN
25%              NaN            NaN            NaN
50%              NaN            NaN            NaN
75%              NaN            NaN            NaN
max              NaN            NaN            NaN

 Check for Null
Group                           False
Department                      False
Workbasket                      False
Case ID                         False
Parent/Child                    False
CustomerType                     True
Assigned OIC                    False
Case Type                       False
SubCategory                     False
Outcome                         False
Source                          False
Channel                         False
Mode                            False
Label                           False
Scheme                          False
Category                        False
Enquiry                          True
ReceiptDate                     False
Created Date                    False
Closed Date                     False
Due Date                         True
Total Days For Resolution       False
Exceeds SLA by how many days    False
ApproverName1                    True
ApproverName2                    True
ApproverName3                    True
ApproverName4                    True
ApproverName5                    True
ApproverName6                    True
ReviewerName1                    True
ReviewerName2                    True
ReviewerName3                    True
ReviewerName4                    True
ReviewerName5                    True
ReviewerName6                    True
dtype: bool

 Dataframe View

,Group,Department,Workbasket,Case ID,Parent/Child,CustomerType,Assigned OIC,Case Type,SubCategory,Outcome,...,ApproverName3,ApproverName4,ApproverName5,ApproverName6,ReviewerName1,ReviewerName2,ReviewerName3,ReviewerName4,ReviewerName5,ReviewerName6
0,ASG,AMD,[S] Silver Support Appeal,S-20240020847,Parent,Member,Juraimi Bin Jamil,Appeal,Agency Schemes,Accepted,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ASG,AMD,[S] Silver Support Appeal,S-20240020847,Parent,Member,Juraimi Bin Jamil,Appeal,Agency Schemes,Accepted,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ASG,AMD,[S] Silver Support Appeal,S-20240020847,Parent,Member,Juraimi Bin Jamil,Appeal,Agency Schemes,Accepted,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ASG,AMD,[S] Silver Support Appeal,S-20240020847,Parent,Member,Juraimi Bin Jamil,Appeal,Agency Schemes,Accepted,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ASG,AMD,[S] Silver Support Appeal,S-20240022842,Parent,Member,Brina Lau Kai Ting,Appeal,Agency Schemes,Rejected,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,RIG,RWD,[S] RS Payout,S-20240087555,Parent,Member,Justin Sunthnasamy,Appeal,CPF Schemes,Accepted,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2576,RIG,RWD,[S] RS Payout,S-20240088218,Parent,Member,Alicia Li Xiaoxu,Enquiry,Enquiry/Service Request,Accepted,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2577,RIG,RWD,[S] RS Payout,S-20240088227,Parent,Member,Jeslyn Tay Fong Ying,Enquiry,Enquiry/Service Request,Accepted,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2578,RIG,RWD,[S] RS Payout,S-20240089389,Parent,Member,Jeslyn Tay Fong Ying,Appeal,CPF Schemes,Rejected,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2579,RIG,RWD,[S] RS Payout,S-20240089868,Parent,Member,Jeslyn Tay Fong Ying,Appeal,CPF Schemes,Rejected,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Data Cleaning for Correspondence Report

In [179]:
df_correspondence_cleaned = df_correspondence.copy()

# turn NaN customer types into "Not Specified"
df_correspondence_cleaned['CustomerType'] = df_correspondence_cleaned['CustomerType'].fillna('Not Specified')

# turn NaN Enquiry into "Not Specified"
df_correspondence_cleaned['Enquiry'] = df_correspondence_cleaned['Enquiry'].fillna('Not Specified')

# remove rows with Due Date = NaN for easier cleaning
df_correspondence_cleaned = df_correspondence_cleaned.dropna(subset='Due Date')

# replace all NaN for Approver and Reviewer with 'Not Specified'
specific_columns = ['ApproverName1', 'ApproverName2', 'ApproverName3', 'ApproverName4', 'ApproverName5', 'ApproverName6', 'ReviewerName1', 'ReviewerName2', 'ReviewerName3', 'ReviewerName4', 'ReviewerName5', 'ReviewerName6']
df_correspondence_cleaned[specific_columns] = df_correspondence_cleaned[specific_columns].fillna("Not Specified")

df_correspondence_cleaned

,Group,Department,Workbasket,Case ID,Parent/Child,CustomerType,Assigned OIC,Case Type,SubCategory,Outcome,...,ApproverName3,ApproverName4,ApproverName5,ApproverName6,ReviewerName1,ReviewerName2,ReviewerName3,ReviewerName4,ReviewerName5,ReviewerName6
0,ASG,AMD,[S] Silver Support Appeal,S-20240020847,Parent,Member,Juraimi Bin Jamil,Appeal,Agency Schemes,Accepted,...,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified
1,ASG,AMD,[S] Silver Support Appeal,S-20240020847,Parent,Member,Juraimi Bin Jamil,Appeal,Agency Schemes,Accepted,...,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified
2,ASG,AMD,[S] Silver Support Appeal,S-20240020847,Parent,Member,Juraimi Bin Jamil,Appeal,Agency Schemes,Accepted,...,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified
3,ASG,AMD,[S] Silver Support Appeal,S-20240020847,Parent,Member,Juraimi Bin Jamil,Appeal,Agency Schemes,Accepted,...,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified
4,ASG,AMD,[S] Silver Support Appeal,S-20240022842,Parent,Member,Brina Lau Kai Ting,Appeal,Agency Schemes,Rejected,...,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,RIG,RWD,[S] RS Payout,S-20240087555,Parent,Member,Justin Sunthnasamy,Appeal,CPF Schemes,Accepted,...,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified
2576,RIG,RWD,[S] RS Payout,S-20240088218,Parent,Member,Alicia Li Xiaoxu,Enquiry,Enquiry/Service Request,Accepted,...,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified
2577,RIG,RWD,[S] RS Payout,S-20240088227,Parent,Member,Jeslyn Tay Fong Ying,Enquiry,Enquiry/Service Request,Accepted,...,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified
2578,RIG,RWD,[S] RS Payout,S-20240089389,Parent,Member,Jeslyn Tay Fong Ying,Appeal,CPF Schemes,Rejected,...,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified
2579,RIG,RWD,[S] RS Payout,S-20240089868,Parent,Member,Jeslyn Tay Fong Ying,Appeal,CPF Schemes,Rejected,...,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified

In [180]:
# save cleaned csv
df_correspondence_cleaned.to_csv('data/Correspondence_Report_cleaned.csv', index=False)

### Adding New 2024 Datas and Concatenate 2022-2024 Cases Data

In [181]:
# adding 2024 data
df_2024 = pd.read_csv("data/2024 Stats.csv")

In [185]:
import csv
from datetime import datetime
import re

def convert_date_format(date_string):
    # Remove day abbreviations (Mon, Tue, Wed, Thu, Fri) from the date string
    date_string = re.sub(r'\s*\(\s*(Mon|Tue|Wed|Thu|Fri|Sat|Sun)\s*\)', '', date_string).strip()
    # Split the date string into day and month
    parts = date_string.split()
    if len(parts) == 2:
        day, month = parts
        try:
            # Convert date format from "1 Jan" to "2024-01-01"
            if month == "Feb" and day == "29":
                return "2024-02-29"
            else:
                date_obj = datetime.strptime(f"{day} {month}", "%d %b")
                return date_obj.replace(year=2024).strftime("%Y-%m-%d")
        except ValueError:
            pass
    return ""

def process_csv(input_file, output_file):
    with open(input_file, 'r') as csv_input, open(output_file, 'w', newline='') as csv_output:
        reader = csv.reader(csv_input, delimiter=';')
        writer = csv.writer(csv_output, delimiter=',')

        # Write header
        writer.writerow(["Date", "Open Balances", "Closed", "New Cases"])

        # Skip header in reader
        next(reader)

        for row in reader:
            # Convert date format
            row[0] = convert_date_format(row[0])
            # Write only the first four columns to output CSV
            writer.writerow(row[:4])

# Input and output file paths
input_file = 'data/2024 Stats.csv'
output_file = "data/2024_Stats_Cleaned.csv"

# Process CSV
process_csv(input_file, output_file)

In [186]:
df_2022 = pd.read_csv("data/2022_Stats_cleaned.csv")
df_2023 = pd.read_csv("data/2023_Stats_cleaned.csv")
df_2024 = pd.read_csv("data/2024_Stats_cleaned.csv")

In [187]:
# Concatenate the data for 2022, 2023 and 2024
df_combined = pd.concat([df_2022, df_2023, df_2024])
df_combined
df_combined.to_csv('data/2022-2024_Stats.csv', index=False)

### Average Case Closure by Agent Type

In [188]:
# adding 2024 data
df_2024 = pd.read_csv("data/2024 Stats.csv")

In [196]:
import csv
from datetime import datetime
import re

def convert_date_format(date_string):
    # Remove day abbreviations (Mon, Tue, Wed, Thu, Fri) from the date string
    date_string = re.sub(r'\s*\(\s*(Mon|Tue|Wed|Thu|Fri|Sat|Sun)\s*\)', '', date_string).strip()
    # Split the date string into day and month
    parts = date_string.split()
    if len(parts) == 2:
        day, month = parts
        try:
            # Convert date format from "1 Jan" to "2024-01-01"
            if month == "Feb" and day == "29":
                return "2024-02-29"
            else:
                date_obj = datetime.strptime(f"{day} {month}", "%d %b")
                return date_obj.replace(year=2024).strftime("%Y-%m-%d")
        except ValueError:
            pass
    return ""

def process_csv(input_file, output_file):
    with open(input_file, 'r') as csv_input, open(output_file, 'w', newline='') as csv_output:
        reader = csv.reader(csv_input, delimiter=';')
        writer = csv.writer(csv_output, delimiter=',')

        # Write header
        writer.writerow(["Date", "Avg Case Closed Per CSE", "Avg Case Closed Per CSA", "Avg Case Closed Per TL", "Avg Case Closed per Temp", "Average Case Closed per CfS", "Avg Case Closed per Sup"])

        # Skip header in reader
        next(reader)

        for row in reader:
            # Convert date format
            row[0] = convert_date_format(row[0])

            # Fill NaNs and round values to one decimal point
            for i in range(1, len(row)):
                if row[i] == "":
                    row[i] = "NaN"
                else:
                    row[i] = round(float(row[i]), 1)

            # Write only the first four columns to output CSV
            writer.writerow([row[0]] + row[4:])

# Input and output file paths
input_file = 'data/2024 Stats.csv'
output_file = "data/Case Closure_2024.csv"

# Process CSV
process_csv(input_file, output_file)

In [202]:
df_2224 = pd.read_csv('data/Case_Closure_(Oct22-Jan24)_cleaned.csv')
df_24 = pd.read_csv('data/Case Closure_2024.csv')

# Concatenate the data for 2022, 2023 and 2024
df_combined = pd.concat([df_2224,df_24])
df_combined
df_combined.to_csv('data/Case_Closure_(Oct22-Mar24).csv', index=False)